import type { VisualStyleDefinition } from '../VisualStyle';

export const classic: VisualStyleDefinition = {
  id: 'classic',
  label: 'Clásico / Corporativo',
  description:
    'Limpio y confiable: bordes suavemente redondeados, sombras sutiles, sin efectos. La base segura para cualquier rubro.',
  tokens: {
    '--ui-radius': '0.625rem',
    '--ui-radius-lg': '0.875rem',
    '--ui-card-bg': 'var(--card)',
    '--ui-card-border-width': '1px',
    '--ui-card-border-color': 'var(--border)',
    '--ui-card-shadow': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    '--ui-card-backdrop': 'none',
    '--ui-button-radius': '0.625rem',
    '--ui-button-border-width': '0px',
    '--ui-button-border-color': 'transparent',
    '--ui-button-shadow': '0 1px 2px 0 rgb(0 0 0 / 0.08)',
    '--ui-button-active-shadow': '0 1px 2px 0 rgb(0 0 0 / 0.08)',
    '--ui-button-active-translate': '0px',
    '--ui-button-weight': '500',
    '--ui-input-bg': 'var(--background)',
    '--ui-input-radius': '0.5rem',
    '--ui-input-border-width': '1px',
    '--ui-input-border-color': 'var(--input)',
    '--ui-input-shadow': 'none',
    '--ui-nav-bg': 'color-mix(in srgb, var(--background) 80%, transparent)',
    '--ui-nav-border': '1px solid var(--border)',
    '--ui-nav-backdrop': 'blur(8px)',
    '--ui-nav-shadow': 'none',
    '--ui-divider-color': 'var(--border)',
    '--ui-divider-width': '1px',
    '--ui-surface-bg': 'color-mix(in srgb, var(--secondary) 40%, var(--background))',
    '--ui-heading-weight': '700',
    '--ui-heading-tracking': '-0.025em',
    '--ui-transition': '160ms ease',
    '--ui-page-bg': 'none',
  },
};
